import java.io.File
import java.io.FileInputStream
import java.util.Properties
import org.gradle.api.Project

/**
 * Generates a common KmpBuildInfo class accessible from all supported targets. Also generates platform specific
 * constants for use outside the KMP module.
 *
 * 1. Run `KmpBuildInfo.generate()` in `kotlin` declaration in shared module
 * 2. Add the following to sourceSets
 *
 * ```kotlin
 * commonMain {
 *     kotlin.srcDir("${layout.buildDirectory.asFile.get().absolutePath}/generated/com/outsidesource/kmpbuild")
 * }
 * ```
 *
 * iOS:
 * 1. Add "#include? "../KmpBuildInfo.xcconfig"" to /iosApp/Configuration/Config.xcconfig (the project level config)
 * 2. Change Info.plist Bundle version string to $(KMP_VERSION) and Bundle version to $(KMP_BUILD)
 * 3. Change Marketing Version in target build settings to $(KMP_VERSION)
 */
data class KmpBuildInfo(val version: String, val build: String, val environment: String) {
    companion object {
        fun read(rootProject: Project): KmpBuildInfo {
            val versionProps =
                Properties().apply { load(FileInputStream(File(rootProject.rootDir, "build.properties"))) }

            return KmpBuildInfo(
                version = versionProps["version"]?.toString() ?: "0.0.0",
                build = versionProps["build"]?.toString() ?: "0",
                environment = versionProps["environment"]?.toString() ?: "prod",
            )
        }

        fun generate(project: Project) {
            val info = read(project)

            // Generate common class
            val buildDir = project.project("shared").layout.buildDirectory.asFile.get()
            val directory = File("$buildDir/generated/com/outsidesource/kmpbuild")
            directory.mkdirs()

            File(directory, "KmpBuildInfo.kt").bufferedWriter().use {
                it.write(
                    """
                    // This file is automatically generated by KMP in build.gradle.kts. Do not change.
                    package com.outsidesource.kmpbuild
                    
                    import kotlinx.serialization.Serializable
                    
                    @Serializable
                    enum class KmpBuildEnvironment {
                        Sandbox,
                        Development,
                        Production,
                    }
                    
                    interface IKmpBuildEnvironmentOverrider {
                        suspend fun setEnvironmentOverride(value: KmpBuildEnvironment)
                        fun getEnvironmentOverride(default: KmpBuildEnvironment): KmpBuildEnvironment
                    }
                    
                    class KmpBuildInfo {
                        companion object {
                            private var environmentOverrider: IKmpBuildEnvironmentOverrider? = null
                            private val defaultEnvironment: KmpBuildEnvironment = ${
                                when (info.environment) {
                                    "sandbox" -> "KmpBuildEnvironment.Sandbox"
                                    "dev" -> "KmpBuildEnvironment.Development"
                                    "prod" -> "KmpBuildEnvironment.Production"
                                    else -> "KmpBuildEnvironment.Production"
                                }
                            }
                            
                            const val version: String = "${info.version}"
                            const val build: String = "${info.build}"
                            
                            val environment: KmpBuildEnvironment
                                get() = environmentOverrider?.getEnvironmentOverride(defaultEnvironment) ?: defaultEnvironment
                            
                            // If the overrider is used, it should be set as early as possible in the app lifecycle
                            fun setEnvironmentOverrider(overrider: IKmpBuildEnvironmentOverrider) {
                                environmentOverrider = overrider
                            }
                        }
                    }
                    """
                        .trimIndent()
                )
            }

            // Generate iOS project file
            val iosDirectory = File(project.layout.projectDirectory.asFile, "iosApp/")

            File(iosDirectory, "KmpBuildInfo.xcconfig").bufferedWriter().use {
                it.write(
                    """
                    // This file is automatically generated by KMP in buildSrc/KmpBuildInfo. Do not change.
                    KMP_VERSION = ${info.version}
                    KMP_BUILD = ${info.build}
                    KMP_ENVIRONMENT = ${info.environment}
                    """
                        .trimIndent()
                )
            }
        }
    }
}
